//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractoFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Appp
    {
        [Key]
        public int AppointmentID { get; set; }
        public string PatientName { get; set; }
        public string MobileNo { get; set; }
        public string PatientCity { get; set; }
        public int Doc_id { get; set; }
        public int TimeSlotID { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime AppointmentDate { get; set; }
        public string Gender { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
    }
}
