//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractoFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Appps = new HashSet<Appp>();
        }
    
        [Key]
        public int Doc_id { get; set; }
        public int Loc_id { get; set; }
        public int Spec_id { get; set; }
        public string Doc_name { get; set; }
        public int Doc_exp { get; set; }
        public decimal Doc_fees { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appp> Appps { get; set; }
        public virtual Location Location { get; set; }
        public virtual Specilization Specilization { get; set; }
    }
}
