//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractoFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PractoEntities3 : DbContext
    {
        public PractoEntities3()
            : base("name=PractoEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appp> Appps { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Signup> Signups { get; set; }
        public virtual DbSet<Specilization> Specilizations { get; set; }
        public virtual DbSet<TimeSlot> TimeSlots { get; set; }

        public System.Data.Entity.DbSet<PractoFinal.Models.AppVM> AppVMs { get; set; }

        public System.Data.Entity.DbSet<PractoFinal.Models.ViewModel.Register> Registers { get; set; }

        public System.Data.Entity.DbSet<PractoFinal.Models.ViewModel.LoginViewModel> LoginViewModels { get; set; }
    }
}
